iteration_num: 2
batch_size: 4
data_parallel_size: 2
devoid_duplication: false
llm_model: "gpt-3.5-turbo"
timeout: 2
data_dir: "./temp/data_train"
project: "EasySAT/"
task: "bump_var_function/"
original: true
original_result: {'time':1,'PAR-2':2}

SAT_solver_file_path: './examples/EasySAT/original_EasySAT/EasySAT.cpp'
eval_timeout: 5
results_save_path: './temp/eval_results/'
eval_data_dir: "./temp/data_eval"
eval_parallel_size: 1
rand_seed: 42
keep_intermediate_results: False